# Numpy (Numerical in python)
    - Numpy is a powerfull library for mathematical operations.
    - We use numpy to create array.

# Array is a collection is homogeneous elements. (Same Data Type)
    - Array's representation is same like list

In [3]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# Creating first array
li = list([4,5,89,45,'A',True])
arr = np.array([56,34,78,99])

In [4]:
li

[4, 5, 89, 45, 'A', True]

In [5]:
 arr

array([56, 34, 78, 99])

In [6]:
print(li)
print(arr)

[4, 5, 89, 45, 'A', True]
[56 34 78 99]


In [7]:
arr = np.array([3,6,78.8,'A','Aman',True])

In [8]:
arr

array(['3', '6', '78.8', 'A', 'Aman', 'True'], dtype='<U32')

In [9]:
arr = np.array([3,67.89,37.9,40])

In [10]:
print(arr)

[ 3.   67.89 37.9  40.  ]


In [11]:
# array, arange, linspace

In [12]:
arr = np.array([56,98,97,99])
print(arr)

[56 98 97 99]


In [13]:
arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [14]:
arr = np.linspace(0.5,5,10)
# linspace (start,stop,number_of_values) # start and stop are included
print(arr)

[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [15]:
arr = np.linspace(0.5,5,25)
print(arr)

[0.5    0.6875 0.875  1.0625 1.25   1.4375 1.625  1.8125 2.     2.1875
 2.375  2.5625 2.75   2.9375 3.125  3.3125 3.5    3.6875 3.875  4.0625
 4.25   4.4375 4.625  4.8125 5.    ]


In [16]:
# Dimensions
# 0thD, 1stD, 2ndD, etc
# Array can work on any dimension

In [17]:
arr = np.array(45)
print(arr)
print(np.ndim(arr))
print(arr.shape)

45
0
()


In [18]:
arr = np.array([45,67,98])
print(arr)
print(np.ndim(arr))
print(arr.shape)

[45 67 98]
1
(3,)


In [20]:
arr = np.array([[45,78,89],[34,67,23],[89,67,345]])
print(arr)
print(np.ndim(arr))
print(arr.shape)

[[ 45  78  89]
 [ 34  67  23]
 [ 89  67 345]]
2
(3, 3)


In [2]:
import numpy as np

In [4]:
arr=np.array([56,89,37,38,84,28])

In [5]:
arr

array([56, 89, 37, 38, 84, 28])

In [6]:
# Built-in functions
# sum, len, min, max, avg

In [8]:
sum(arr)

np.int64(332)

In [9]:
len(arr)

6

In [14]:
print("Average:", sum(arr)/len(arr))

Average: 55.333333333333336


In [10]:
min(arr)

np.int64(28)

In [11]:
max(arr)

np.int64(89)

In [15]:
# WAP to add all the elements of an array

In [16]:
arr

array([56, 89, 37, 38, 84, 28])

In [17]:
add = 0
for ele in arr:
    add=add+ele

In [23]:
print("Sum:",add)

Sum: 332


In [24]:
# WAP to find MAX value of an array

In [25]:
arr

array([56, 89, 37, 38, 84, 28])

In [26]:
maxx = arr[0]
for ele in arr:
    if maxx < ele:
        maxx=ele

In [27]:
print("Max:",maxx)

Max: 89


In [28]:
# WAP to find MIN value of an array

In [29]:
arr

array([56, 89, 37, 38, 84, 28])

In [31]:
minn = arr[0]
for ele in arr:
    if ele < minn:
        minn=ele

In [32]:
print("Min:",minn)

Min: 28


In [33]:
# WAP to count values of an array

In [34]:
count = 0
for ele in arr:
    count=count+1

In [35]:
count

6

In [36]:
arr = np.array([567,892,368,392,583,517,439,153,953,156,948,555])

In [37]:
sum(arr)

np.int64(6523)

In [38]:
# WAP to add only even numbers

In [39]:
add = 0
for ele in arr:
    if ele%2==0:
        add=add+ele

In [40]:
add

np.int64(2756)

In [45]:
arr = np.array([[1,6,3],[4,8,2],[5,7,9]])

In [46]:
arr

array([[1, 6, 3],
       [4, 8, 2],
       [5, 7, 9]])

In [43]:
np.ndim(arr)

2

In [44]:
# Matrix

In [47]:
matrix1 = np.array([[1,6,3],[4,8,2],[5,7,9]])

In [48]:
matrix1

array([[1, 6, 3],
       [4, 8, 2],
       [5, 7, 9]])

In [49]:
matrix2 = np.array([[1,3,6],[2,5,7],[7,4,3]])

In [50]:
matrix2

array([[1, 3, 6],
       [2, 5, 7],
       [7, 4, 3]])

In [51]:
matrix1+matrix2

array([[ 2,  9,  9],
       [ 6, 13,  9],
       [12, 11, 12]])

In [52]:
matrix1.shape , matrix2.shape

((3, 3), (3, 3))

In [53]:
np.nan

nan

In [55]:
np.zeros(3)

array([0., 0., 0.])

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
np.ones(3)

array([1., 1., 1.])

In [59]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [61]:
# identical matrix

In [63]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [68]:
np.eye(3,4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [69]:
np.full(3,5)

array([5, 5, 5])

In [70]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [71]:
np.random.random(4)

array([0.11184414, 0.80686963, 0.44960288, 0.70525487])

In [72]:
np.random.random((3,4))

array([[0.10539439, 0.3966439 , 0.90706624, 0.42217863],
       [0.11401937, 0.07235159, 0.08619764, 0.436196  ],
       [0.69965707, 0.16175425, 0.88687189, 0.16540195]])

In [73]:
np.random.randint(10)

4

In [75]:
np.random.randint(1,100)

65

In [76]:
# np.random.randint(start,stop,shape_of_array)

In [77]:
np.random.randint(1,20,(4,4))

array([[ 4,  6,  8, 12],
       [ 7,  6,  4, 19],
       [ 9,  4, 19,  1],
       [16, 16, 17,  8]], dtype=int32)